services:
  rwmarkable:
    image: ghcr.io/fccview/rwmarkable:latest
    container_name: rwmarkable
    user: "1000:1000"
    ports:
      # Feel free to change the FIRST port, 3000 is very common 
      # so I like to map it to something else (in this case 1122)
      - "1122:3000"
    volumes:
      # --- MOUNT DATA DIRECTORY
      # This is needed for persistent data storage on YOUR host machine rather than inside the docker volume.
      - ./data:/app/data:rw
      - ./config:/app/config:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Uncomment to enable HTTPS
      # - HTTPS=true
    # --- DEFAULT PLATFORM IS SET TO AMD64, UNCOMMENT TO USE ARM64.
    #platform: linux/arm64